- name: install aptitude
  command: apt-get install aptitude

- name: update the apt package index i.e. apt-get update
  apt: update_cache=yes

- name: upgrade system packages i.e. apt-get upgrade
  apt: upgrade=yes

- name: Install packages via apt
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - nodejs
    - npm
    - qemu-kvm
    - libvirt-bin
    - ubuntu-vm-builder
    - bridge-utils
    - gradle

- name: add existing user '{{ user }}' to group kvm
  user:
    name: '{{ user }}'
    groups: kvm
    append: yes
